Repository Girl-Code-It/Opportunity-Calendar-Frontend, pull requests merged in 2021-04, with the labels that each got.

#156 Link to opportunities added in navbar
  src/Components/HomePage/Sections/KnowAbout.js
  src/Components/HomePage/Sections/Navbar.js
Labels: GSSOC21, LEVEL1

#172 (feature) - Added Custom Scrollbar
  src/App.css
  src/App.js
Labels: GSSOC21, LEVEL1

#177 dynamic copyright year
  src/Components/Footer/Footer.js
Labels: GSSOC21, LEVEL0

#178 Added animations
  src/Assets/AboutUs.gif
  src/Assets/banner.gif
  src/CSS/Banner.module.css
  src/Components/HomePage/Sections/AboutUs.js
  src/Components/HomePage/Sections/Banner.js
Labels: GSSOC21, LEVEL1

#183 Update README.md
  README.md
Labels: GSSOC21, LEVEL0

#186 Implemented the show/hide password funtionality
  src/CSS/SignupLogin.module.css
  src/Components/SignupLogin/Login.js
  src/Components/SignupLogin/SignUp.js
Labels: GSSOC21, LEVEL1

#189 (feature)- added faq data
  src/CSS/Navbar.module.css
  src/Components/HomePage/Sections/FAQ_Data.js
Labels: GSSOC21, LEVEL0

#202 fixes #198
  src/CSS/Footer.module.css
  src/Components/Footer/Footer.js
Labels: GSSOC21, LEVEL1

#201 (Feature/Styling) Opportunity Card Updated
  package-lock.json
  src/Components/ViewOpportunity/Opportunity.module.css
  src/Components/ViewOpportunity/OpportunityCard.js
Labels: GSSOC21, LEVEL2

#208 update contributing.md
  contributing.md
Labels: GSSOC21, LEVEL0

#203 View Opportunity Page revamp(#164)
  src/CSS/Navbar.module.css
  src/Components/PostOpportunity/sections/Navbar.js
  src/Components/ViewOpportunity/Navbar.js
  src/Components/ViewOpportunity/Opportunity.module.css
  src/Components/ViewOpportunity/index.js
Labels: GSSOC21, LEVEL2

#214 Auto-labeling of Gssoc21
  .github/workflow/autoLabel.yaml
Labels: GSSOC21, LEVEL1

#213 feat: Arrangement of Buttons in HomePage #205
  package-lock.json
  src/CSS/AboutUs.module.css
Labels: GSSOC21, LEVEL1

#223 Fixed UI gitch and clean up the code
  src/Components/Footer/Footer.js
  src/Components/HomePage/HomePage.js
  src/Components/PostOpportunity/PostOpportunity.js
  src/Components/PostOpportunity/sections/CodingComp/CodingComp.js
  src/Components/PostOpportunity/sections/FullTime/FullTime.js
  src/Components/PostOpportunity/sections/Internships/Internships.js
  src/Components/PostOpportunity/sections/Navbar.js
  src/Components/PostOpportunity/sections/Scholarships/Scholarships.js
  src/Components/PostOpportunity/sections/TechConf/TechConf.js
  src/Components/ViewOpportunity/Navbar.js
  src/Components/ViewOpportunity/Opportunity.module.css
  src/Components/ViewOpportunity/OpportunityCard.js
  src/Components/ViewOpportunity/index.js
Labels: GSSOC21, LEVEL2

#230 View opportunity api changes done (#228)
  src/App.js
  src/Components/ViewOpportunity/OpportunityCard.js
  src/Components/ViewOpportunity/index.js
Labels: GSSOC21, LEVEL2

#199 react context api implemented
  src/Hooks/reducer.js
  src/Hooks/stateProvider.js
  src/Hooks/user.actions.js
  src/index.js
Labels: GSSOC21, LEVEL2

#231 github social link added
  src/Components/Footer/Footer.js
  src/__tests__/Footer/Footer.test.js
Labels: GSSOC21, LEVEL0
