Repository Girl-Code-It/Opportunity-Calendar-Frontend, pull requests merged in 2021-05, with the labels that each got.

#233 Updated api to create new opportunity
  src/Components/PostOpportunity/sections/CodingComp/CodingCompForm.js
  src/Components/PostOpportunity/sections/FullTime/FullTimeForm.js
  src/Components/PostOpportunity/sections/Hackathons/HackathonsForm.js
  src/Components/PostOpportunity/sections/Internships/InternshipForm.js
  src/Components/PostOpportunity/sections/Scholarships/ScholarshipForm.js
  src/Components/PostOpportunity/sections/TechConf/TechConfForm.js
  src/Components/ViewOpportunity/index.js
Labels: GSSOC21, LEVEL3

#239 Remaking of signIn/signUp pages
  src/Assets/login.svg
  src/Assets/signup.svg
  src/CSS/SignupLogin.module.css
  src/Components/SignupLogin/Login.js
  src/Components/SignupLogin/SignUp.js
Labels: GSSOC21, LEVEL1

#258 feedback form
  src/App.js
  src/CSS/Navbar.module.css
  src/CSS/Opportunity.module.css
  src/Components/Footer/Footer.js
  src/Components/Forget/Forget.js
  src/Components/ViewOpportunity/CommonComponents.js
  src/Components/ViewOpportunity/Navbar.js
Labels: GSSOC21, LEVEL1

#261 Combine multiple Post Opportunity Forms into One form #254
  package-lock.json
  package.json
  src/App.js
  src/Components/PostOpportunity/Navbar.js
  src/Components/PostOpportunity/PostOpportunity.js
  src/Components/PostOpportunity/PostOpportunityForm.js
  src/Components/PostOpportunity/sections/CodingComp/CodingComp.js
  src/Components/PostOpportunity/sections/FullTime/FullTime.js
  src/Components/PostOpportunity/sections/FullTime/FullTimeForm.js
  src/Components/PostOpportunity/sections/Hackathons/Hackathons.js
  src/Components/PostOpportunity/sections/Hackathons/HackathonsForm.js
  src/Components/PostOpportunity/sections/Internships/InternshipForm.js
  src/Components/PostOpportunity/sections/Internships/Internships.js
  src/Components/PostOpportunity/sections/Scholarships/ScholarshipForm.js
  src/Components/PostOpportunity/sections/Scholarships/Scholarships.js
  src/Components/PostOpportunity/sections/TechConf/TechConf.js
  src/Components/PostOpportunity/sections/TechConf/TechConfForm.js
  src/Components/ViewOpportunity/Navbar.js
  src/Components/ViewOpportunity/index.js
Labels: GSSOC21, LEVEL2

#259 Updated files for Post Opportunity
  src/App.css
  src/CSS/AboutUs.module.css
  src/CSS/CodingCompForm.module.css
  src/CSS/Footer.module.css
  src/CSS/Forget.module.css
  src/CSS/HackathonForm.module.css
  src/CSS/InternshipForm.module.css
  src/CSS/KnowAbout.module.css
  src/CSS/Navbar.module.css
  src/CSS/Opportunity.module.css
  src/CSS/PostForm.module.css
  src/CSS/ScholarshipForm.module.css
  src/CSS/SignupLogin.module.css
  src/CSS/SocialIcons.module.css
  src/CSS/TechConfForm.module.css
  src/Components/Footer/Footer.js
  src/Components/Forget/Forget.js
  src/Components/HomePage/Sections/Navbar.js
  src/Components/PostOpportunity/AddDiv.js
  src/Components/PostOpportunity/Navbar.js
  src/Components/PostOpportunity/PostOpportunity.js
  src/Components/PostOpportunity/PostOpportunityForm.js
Labels: GSSOC21, LEVEL3

#266 Optimized the project directory.
  src/CSS/PostForm.module.css
  src/Components/PostOpportunity/PostOpportunity.js
Labels: GSSOC21, LEVEL1
