Repository Girl-Code-It/Opportunity-Calendar-Frontend, pull requests merged in 2021-03, with the labels that each got.

#52 Fixed Scroll Error Footer.js
  src/Components/Footer/Footer.js
Labels: wont-merge

#65 (feature/FAQ)-Added FAQ component
  src/Assets/arrow.png
  src/Assets/arrowup.png
  src/CSS/FAQ.module.css
  src/Components/HomePage/HomePage.js
  src/Components/HomePage/Sections/FAQ_Cards.js
  src/Components/HomePage/Sections/FAQ_Data.js
  src/Components/HomePage/Sections/FAQ_main.js
Labels: GSS0C21, LEVEL1

#77 Fixed Button Outline When It Get Clicked
  .gitignore
  src/CSS/Banner.module.css
  src/CSS/CodingCompForm.module.css
  src/CSS/FullTimeForm.module.css
  src/CSS/HackathonForm.module.css
  src/CSS/InternshipForm.module.css
  src/CSS/Navbar.module.css
  src/CSS/ScholarshipForm.module.css
  src/CSS/TechConfForm.module.css
  src/Components/ViewOpportunity/Opportunity.module.css
Labels: GSS0C21, LEVEL1

#83 (feature/Contact Us) - Added Contact Us component to homepage.
  src/CSS/ContactUs.module.css
  src/Components/HomePage/HomePage.js
  src/Components/HomePage/Sections/ContactUs.js
Labels: GSSOC21, LEVEL1

#80 Added Hover over Buttons
  src/CSS/Banner.module.css
Labels: GSSOC21, LEVEL0

#113 Added tech stack
  README.md
Labels: GSSOC21, LEVEL0

#112 Contributor
  README.md
Labels: GSSOC21, LEVEL0

#136 Favicon Added
  package-lock.json
  public/favicon.ico
  public/index.html
Labels: GSSOC21, LEVEL0
